(require 'ob-tangle)
(let* ((init-org (file-truename (expand-file-name "init.org" user-emacs-directory)))
       (config-el (expand-file-name "emacs-config.el" (file-name-directory init-org))))
  (org-babel-tangle-file init-org)
  (load config-el))
