links:
  - src: config/emacs/init.el
    dst: ~/.emacs.d/init.el
  - src: config/emacs/init.org
    dst: ~/config/emacs/init.org
  - src: config/zsh/.zshrc
    dst: ~/.zshrc
  - src: config/tmux/.tmux.conf
    dst: ~/.tmux.conf
  - src: config/emacs/lisp/corfu-terminal.el
    dst: ~/.emacs.d/lisp/corfu-terminal.el
  - src: config/emacs/lisp/popon.el
    dst: ~/.emacs.d/lisp/popon.el