#+STARTIP: overview

* Base Setup
** quelpa
#+begin_src emacs-lisp
  (unless (package-installed-p 'quelpa)
    (with-temp-buffer
      (url-insert-file-contents "https://raw.githubusercontent.com/quelpa/quelpa/master/quelpa.el")
      (eval-buffer)
      (quelpa-self-upgrade)))

  (quelpa
   '(quelpa-use-package
     :fetcher git
     :url "https://github.com/quelpa/quelpa-use-package.git"))
  (require 'quelpa-use-package)
#+end_src

#+RESULTS:
: quelpa-use-package
** straight
#+begin_src emacs-lisp
  (defvar bootstrap-version)
  (let ((bootstrap-file
	 (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
	(bootstrap-version 6))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
	  (url-retrieve-synchronously
	   "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
	   'silent 'inhibit-cookies)
	(goto-char (point-max))
	(eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))
#+end_src

** Interface Setup
   Sets up the interface

   #+BEGIN_SRC emacs-lisp
     (setq inhibit-startup-message t)

     (fset 'yes-or-no-p 'y-or-n-p)
     (global-set-key (kbd "<f5>") 'revert-buffer)

     (defalias 'list-buffers 'ibuffer-other-window)

     (global-hl-line-mode t)

     (set-face-background 'hl-line "#5e5e5e")

     (use-package beacon
       :ensure t
       :config
       (beacon-mode 1)
       (setq beacon-color "#666000"))

     (use-package hungry-delete
       :ensure t
       :config
       (global-hungry-delete-mode))

     (add-to-list 'hungry-delete-except-modes 'minibuffer-mode)

     (use-package expand-region
       :ensure t
       :config
       (global-set-key (kbd "C-q") 'er/expand-region))

     (use-package iedit
       :ensure t
       :config
       (global-set-key (kbd "M-q") 'iedit-mode))

     (setq save-interprogram-paste-before-kill t)

     (global-auto-revert-mode 1)
     (setq auto-revert-verbose nil)

     (add-hook 'before-save-hook 'my-prog-nuke-trailing-whitespace)

     (defun my-prog-nuke-trailing-whitespace ()
       (when (derived-mode-p 'prog-mode)
	 (delete-trailing-whitespace)))

   #+END_SRC
** avy
#+begin_src emacs-lisp
  (use-package avy
    :ensure t
    :config
    (setq avy-timeout-seconds 0.5)
    :bind
    (("C-c SPC" . avy-goto-char-timer)
     ("M-g g" . avy-goto-line))
    )

  (add-hook 'org-mode-hook
	    (lambda ()
	      (local-unset-key (kbd "C-c SPC"))))
#+end_src

#+RESULTS:
| (lambda nil (local-unset-key (kbd C-c SPC))) | (lambda nil (org-bullets-mode 1)) | #[0 \301\211\207 [imenu-create-index-function org-imenu-get-tree] 2] | er/add-org-mode-expansions | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-show-all append local] 5] | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-babel-show-result-all append local] 5] | org-babel-result-hide-spec | org-babel-hide-all-hashes |

** which-key
   Sets up the which-key package

   #+BEGIN_SRC emacs-lisp
     (use-package which-key
       :ensure t
       :config (which-key-mode))
   #+END_SRC

** theme
   #+begin_src emacs-lisp
  (use-package flatland-theme
    :ensure t
    :config (load-theme 'flatland t))

  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)

  (use-package rainbow-delimiters
    :ensure t
    :config
    (add-hook 'python-mode-hook 'rainbow-delimiters-mode)
    (add-hook 'emacs-lisp-mode 'rainbow-delimiters-mode)
    (add-hook 'lisp-mode 'rainbow-delimiters-mode)
    )
   #+end_src

   #+RESULTS:
   : t

** mode-line
#+begin_src emacs-lisp
  (use-package all-the-icons
    :ensure t
    )

  (use-package fontset
    :ensure t
    :straight (:type built-in)
    :config
    (when (member "Symbola" (font-family-list))
      (set-fontset-font
       t 'symbol "Symbola" nil)))

       ;; (display-time-mode t) ;; required to show time in the mode line

  (use-package lambda-line
    :ensure t
    :straight (:type git :host github :repo "lambda-emacs/lambda-line") 
    :custom
    (lambda-line-vc-symbol " | ")
    (lambda-line-icon-time -1)
    (lambda-line-position 'bottom) ;; Set position of status-line 
    (lambda-line-abbrev t) ;; abbreviate major modes
    (lambda-line-hspace "  ")  ;; add some cushion
    (lambda-line-prefix t) ;; use a prefix symbol
    (lambda-line-prefix-padding nil) ;; no extra space for prefix 
    (lambda-line-status-invert nil)  ;; no invert colors
    (lambda-line-gui-ro-symbol  " ⨂") ;; symbols
    (lambda-line-gui-mod-symbol " ⬤") 
    (lambda-line-gui-rw-symbol  " ◯") 
    (lambda-line-space-top +.30)  ;; padding on top and bottom of line
    (lambda-line-space-bottom -.30)
    (lambda-line-symbol-position 0.1) ;; adjust the vertical placement of symbol
    (lambda-line-git-diff-mode-line t)
    (lambda-line-syntax t)
    :config
    ;; activate lambda-line 
    (lambda-line-mode)
    )
#+end_src

#+RESULTS:
: t

** ace-window
   ace-window setup.

   #+begin_src emacs-lisp
     (use-package ace-window
       :ensure t
       :init
       (global-set-key [remap other-window] 'ace-window)
       )

   #+end_src

   #+RESULTS:
   : ace-window

** counsel
    counsel setup.
      
    #+BEGIN_SRC emacs-lisp
      (use-package counsel
	:ensure t
	:bind
	(("M-y" . counsel-yank-pop)
	 :map ivy-minibuffer-map
	 ("M-y" . ivy-next-line)))
    #+END_SRC

** ivy
   ivy setup
   
   #+BEGIN_SRC emacs-lisp
     (use-package ivy
      :ensure t
      :diminish (ivy-mode)
      :bind (("C-x b" . ivy-switch-buffer))
      :config
      (ivy-mode 1)
      (setq ivy-use-virtual-buffers t)
      (setq ivy-count-format "%d/%d ")
      (setq ivy-display-style 'fancy))
   #+END_SRC

** swiper
   swiper setup.
   
   #+begin_src emacs-lisp
       (use-package swiper
	 :ensure t
	 :bind (("C-s" . swiper)
		("C-r" . swiper)
		("C-c C-r" . ivy-resume)
		("M-x" . counsel-M-x)
		("C-x C-f" . counsel-find-file))
	 :config
	 (progn
	   (ivy-mode 1)
	   (setq ivy-use-virtual-buffers t)
	   (setq ivy-display-style 'fancy)
	   (define-key read-expression-map (kbd "C-r") 'counsel-expression-history)
	   ))
   #+end_src
** projectile
   projectile setup.

   #+BEGIN_SRC emacs-lisp
     (use-package projectile
       :ensure t
       :config
       (projectile-global-mode)
       (setq projectile-completion-system 'ivy))

     (use-package counsel-projectile
       :ensure t
       :config
       (counsel-projectile-mode))

     (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
   #+END_SRC
** yassnippet

#+BEGIN_SRC emacs-lisp
  (use-package yasnippet
    :ensure t
    :config
    (yas-global-mode)
    )

  (use-package yasnippet-snippets
    :ensure t
    )

#+END_SRC

#+RESULTS:

** magit
   magit (git) setup.  For some reason the keybinding wasn't working by default (unsure if this is desired behavior or not), but I added it manually.
   
   #+BEGIN_SRC emacs-lisp
     (use-package magit
       :ensure t
       :config
       (global-set-key (kbd "C-c g") 'magit-status)
       )
   #+END_SRC

   #+RESULTS:
   : t

* Various Language Environment Setups
** [elpy] New Python Setup
#+BEGIN_SRC emacs-lisp
  (use-package elpy
    :ensure t
    :init
    (elpy-enable))

  (add-hook 'elpy-mode-hook (lambda ()
			      (add-hook 'before-save-hook
					'elpy-black-fix-code nil t)))

  (when (load "flycheck" t t)
    (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
    (add-hook 'elpy-mode-hook 'flycheck-mode))

  (setq python-flymake-command '("/Users/rjohn/.pyenv/shims/flake8" "--config=/Users/rjohn/flake8.ini" "-"))  
  (setq python-check-command "/Users/rjohn/.pyenv/shims/flake8 --config=/Users/rjohn/flake8.ini")
  (setq elpy-syntax-check-command python-check-command)

  (use-package importmagic
      :ensure t
      :config
      (add-hook 'python-mode-hook 'importmagic-mode))

  (define-key importmagic-mode-map (kbd "C-c C-l") 'importmagic-fix-symbol-at-point)
  ; (setq importmagic-be-quiet t)
  ; (add-to-list 'ivy-ignore-buffers "\\*epc con")

  (setq flycheck-flake8rc "/Users/rjohn/flake8.ini")

  (defun company-yasnippet-or-completion ()
    "Solve company yasnippet conflicts."
    (interactive)
    (let ((yas-fallback-behavior
	   (apply 'company-complete-common nil)))
      (yas-expand)))

  (add-hook 'company-mode-hook
	    (lambda ()
	      (substitute-key-definition
	       'company-complete-common
	       'company-yasnippet-or-completion
	       company-active-map)))

#+END_SRC

#+RESULTS:
| (lambda nil (substitute-key-definition 'company-complete-common 'company-yasnippet-or-completion company-active-map)) | company-mode-set-explicitly |

* org-mode setup
** org-modern
#+begin_src emacs-lisp
  (use-package org-modern
    :ensure t
    :config
    (setq org-auto-align-tags nil)
    (setq org-tags-column 0)
    (setq org-catch-invisible-edits 'show-and-error)
    (setq org-special-ctrl-a/e t)
    (setq org-insert-heading-respect-content t)
    (setq org-hide-emphasis-markers t)
    (setq org-pretty-entities t)
	
	
    (add-hook 'org-mode-hook #'org-modern-mode)
    (add-hook 'org-agenda-finalize-hook #'org-modern-agenda)
    )

#+end_src

#+RESULTS:
: t

** org-capture setup
   org-capture setup.  The fun stuff.
   
   #+BEGIN_SRC emacs-lisp
     (global-set-key (kbd "C-c c") 'org-capture)

     (setq org-capture-templates
	   '(("n" "Note" entry (file+headline "~/Dropbox/src/orgfiles/notes.org" "Notes")
	      "* %?\n%T\n%F\n\n%i")
	     ("m" "Meeting Note" entry (file+olp+datetree "~/Dropbox/src/orgfiles/notes.org" "Meeting Notes")
	      "* %?\n\n")
	     ("l" "Link" entry (file+headline "~/Dropbox/src/orgfiles/notes.org" "Links")
	      "* %? %^L \n%T")
	     ("t" "To Do Item" entry (file+headline "~/Dropbox/src/orgfiles/i.org" "To Do Items")
	      "* TODO %?\n %i\n\n" :prepend t)
	     ("d" "Deadline Item" entry (file+headline "~/Dropbox/src/orgfiles/i.org" "Deadlines")
	      "* TODO %?\nDEADLINE: %^T \n %i\n\n" :prepend t)
	     ("j" "Journal" entry (file+datetree "~/Dropbox/src/orgfiles/journal.org")
	      "* %?\nEntered on %U\n  %i\n  %a\n\n")))
   #+END_SRC

   #+RESULTS:
   | n | Note | entry | (file+headline ~/Dropbox/src/orgfiles/notes.org Notes) | * %? |

** org-gcal
   org-gcal config.

   Some sort of duplication problem, working on it...  As of now it doesn't work.

   #+BEGIN_SRC emacs-lisp :tangle no
     (setq package-check-signature nil)

     (use-package org-gcal
       :ensure t
       :config
       (setq org-gcal-client-id "CLIENT ID"
	     org-gcal-client-secret "SECRET"
	     org-gcal-file-alist '(("johnrod.john@gmail.com" . "~/Dropbox/src/orgfiles/cal.org"))))

   #+END_SRC

   #+RESULTS:
   : t

** org-agenda
   org-agenda

#+begin_src emacs-lisp :tangle no
  (use-package org-super-agenda
    :ensure t
    :config
    (org-super-agenda-mode)
    )

    (let ((org-super-agenda-groups
	   '((:auto-group t))))
      (org-agenda-list))
#+end_src

   #+BEGIN_SRC emacs-lisp
  (setq org-agenda-files (list "~/Dropbox/src/orgfiles/notes.org"
			       "~/Dropbox/src/orgfiles/journal.org"			     
			       "~/Dropbox/src/orgfiles/i.org"))

  (define-key global-map "\C-ca" 'org-agenda)

  (setq org-agenda-custom-commands
	'(("c" "Simple agenda view"
	   ((agenda "")
	    (alltodo "")))))
   #+END_SRC

   #+RESULTS:
   | c | Simple agenda view | ((agenda ) (alltodo )) |

* Shortcuts to remember
  - C-( starts a macro
  - C-) stops a macro
  - C-e runs a macro
  - C-, C-. C-? for python documentation
  - C-x u for undo tree
  - <s-TAB
  - C-q expand-region thing
  - M-q iedit mode
  - C-x n narrow-widen-dwim
  - C-c C-e w surrounds marked area in html tag
  - C-c C-f folds html   


   
   
